language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

# install python dependencies including this package in the travis
# virtualenv
install:
  - ./provision/python.sh

script:
    - pycodestyle mediawiki/
    - coverage run --source=mediawiki setup.py test
    - ./scripts/py-lint.sh

# commands to run after the tests successfully complete
after_success:
  - coveralls
